# Source: kubeflow-trainer/templates/webhook/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-trainer-webhook-cert
  namespace: kubeflow-system
  labels:
    app.kubernetes.io/name: kubeflow-trainer
    app.kubernetes.io/instance: kubeflow-trainer
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/component: webhook
data:
  ca.crt: ""
  ca.key: ""
  tls.crt: ""
  tls.key: ""
