# Source: kubeflow-trainer/templates/rbac/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-trainer-controller
  labels:
    app.kubernetes.io/name: kubeflow-trainer
    app.kubernetes.io/instance: kubeflow-trainer
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/component: controller
rules:
  - apiGroups:
      - ""
    resources:
      - limitranges
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - node.k8s.io
    resources:
      - runtimeclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - jobset.x-k8s.io
    resources:
      - jobsets
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - scheduling.x-k8s.io
    resources:
      - podgroups
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - trainer.kubeflow.org
    resources:
      - clustertrainingruntimes
      - trainingruntimes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - trainer.kubeflow.org
    resources:
      - trainjobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - trainer.kubeflow.org
    resources:
      - trainjobs/finalizers
      - trainjobs/status
    verbs:
      - get
      - update
      - patch
