# coding: utf-8

"""
    Kubeflow Training SDK

    Python SDK for Kubeflow Training  # noqa: E501

    The version of the OpenAPI document: v1.7.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

from kubeflow.training.models import *
from kubeflow.training.models.v1_table import V1Table  # noqa: E501
from kubeflow.training.rest import ApiException

class TestV1Table(unittest.TestCase):
    """V1Table unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1Table
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubeflow.training.models.v1_table.V1Table()  # noqa: E501
        if include_optional :
            return V1Table(
                api_version = '0', 
                column_definitions = [
                    V1TableColumnDefinition(
                        description = '0', 
                        format = '0', 
                        name = '0', 
                        priority = 56, 
                        type = '0', )
                    ], 
                kind = '0', 
                metadata = V1ListMeta(
                    continue = '0', 
                    remaining_item_count = 56, 
                    resource_version = '0', 
                    self_link = '0', ), 
                rows = [
                    V1TableRow(
                        cells = [
                            None
                            ], 
                        conditions = [
                            V1TableRowCondition(
                                message = '0', 
                                reason = '0', 
                                status = '0', 
                                type = '0', )
                            ], 
                        object = kubeflow.training.models.k8s/io/apimachinery/pkg/runtime/raw_extension.k8s.io.apimachinery.pkg.runtime.RawExtension(), )
                    ]
            )
        else :
            return V1Table(
                column_definitions = [
                    V1TableColumnDefinition(
                        description = '0', 
                        format = '0', 
                        name = '0', 
                        priority = 56, 
                        type = '0', )
                    ],
                rows = [
                    V1TableRow(
                        cells = [
                            None
                            ], 
                        conditions = [
                            V1TableRowCondition(
                                message = '0', 
                                reason = '0', 
                                status = '0', 
                                type = '0', )
                            ], 
                        object = kubeflow.training.models.k8s/io/apimachinery/pkg/runtime/raw_extension.k8s.io.apimachinery.pkg.runtime.RawExtension(), )
                    ],
        )

    def testV1Table(self):
        """Test V1Table"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
