# coding: utf-8

"""
    Kubeflow Training SDK

    Python SDK for Kubeflow Training  # noqa: E501

    The version of the OpenAPI document: v1.7.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

from kubeflow.training.models import *
from kubeflow.training.models.v1_apply_options import V1ApplyOptions  # noqa: E501
from kubeflow.training.rest import ApiException

class TestV1ApplyOptions(unittest.TestCase):
    """V1ApplyOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1ApplyOptions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubeflow.training.models.v1_apply_options.V1ApplyOptions()  # noqa: E501
        if include_optional :
            return V1ApplyOptions(
                api_version = '0', 
                dry_run = [
                    '0'
                    ], 
                field_manager = '0', 
                force = True, 
                kind = '0'
            )
        else :
            return V1ApplyOptions(
                field_manager = '0',
                force = True,
        )

    def testV1ApplyOptions(self):
        """Test V1ApplyOptions"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
