# coding: utf-8

"""
    TFOpeartor

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tfoperator.sdk
from models.io_k8s_apimachinery_pkg_util_intstr_int_or_string import IoK8sApimachineryPkgUtilIntstrIntOrString  # noqa: E501
from tfoperator.sdk.rest import ApiException


class TestIoK8sApimachineryPkgUtilIntstrIntOrString(unittest.TestCase):
    """IoK8sApimachineryPkgUtilIntstrIntOrString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgUtilIntstrIntOrString(self):
        """Test IoK8sApimachineryPkgUtilIntstrIntOrString"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tfoperator.sdk.models.io_k8s_apimachinery_pkg_util_intstr_int_or_string.IoK8sApimachineryPkgUtilIntstrIntOrString()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
