# coding: utf-8

"""
    TFOpeartor

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tfoperator.sdk
from models.io_k8s_api_core_v1_resource_quota_status import IoK8sApiCoreV1ResourceQuotaStatus  # noqa: E501
from tfoperator.sdk.rest import ApiException


class TestIoK8sApiCoreV1ResourceQuotaStatus(unittest.TestCase):
    """IoK8sApiCoreV1ResourceQuotaStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1ResourceQuotaStatus(self):
        """Test IoK8sApiCoreV1ResourceQuotaStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tfoperator.sdk.models.io_k8s_api_core_v1_resource_quota_status.IoK8sApiCoreV1ResourceQuotaStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
