# coding: utf-8

"""
    TFOpeartor

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tfoperator.sdk
from models.io_k8s_apimachinery_pkg_api_resource_quantity import IoK8sApimachineryPkgApiResourceQuantity  # noqa: E501
from tfoperator.sdk.rest import ApiException


class TestIoK8sApimachineryPkgApiResourceQuantity(unittest.TestCase):
    """IoK8sApimachineryPkgApiResourceQuantity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApiResourceQuantity(self):
        """Test IoK8sApimachineryPkgApiResourceQuantity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tfoperator.sdk.models.io_k8s_apimachinery_pkg_api_resource_quantity.IoK8sApimachineryPkgApiResourceQuantity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
