# coding: utf-8

"""
    TFOpeartor

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tfoperator.sdk
from models.io_k8s_apimachinery_pkg_apis_meta_v1_export_options import IoK8sApimachineryPkgApisMetaV1ExportOptions  # noqa: E501
from tfoperator.sdk.rest import ApiException


class TestIoK8sApimachineryPkgApisMetaV1ExportOptions(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1ExportOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1ExportOptions(self):
        """Test IoK8sApimachineryPkgApisMetaV1ExportOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tfoperator.sdk.models.io_k8s_apimachinery_pkg_apis_meta_v1_export_options.IoK8sApimachineryPkgApisMetaV1ExportOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
