# coding: utf-8

"""
    TFOpeartor

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tfoperator.sdk
from models.io_k8s_api_core_v1_event_series import IoK8sApiCoreV1EventSeries  # noqa: E501
from tfoperator.sdk.rest import ApiException


class TestIoK8sApiCoreV1EventSeries(unittest.TestCase):
    """IoK8sApiCoreV1EventSeries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1EventSeries(self):
        """Test IoK8sApiCoreV1EventSeries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tfoperator.sdk.models.io_k8s_api_core_v1_event_series.IoK8sApiCoreV1EventSeries()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
