# Source: kubeflow-trainer/templates/controller/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-trainer-controller
  namespace: kubeflow-system
  labels:
    app.kubernetes.io/name: kubeflow-trainer
    app.kubernetes.io/instance: kubeflow-trainer
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeflow-trainer
      app.kubernetes.io/instance: kubeflow-trainer
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubeflow-trainer
        app.kubernetes.io/instance: kubeflow-trainer
        app.kubernetes.io/part-of: kubeflow
        app.kubernetes.io/component: controller
    spec:
      containers:
        - name: controller
          image: docker.io/kubeflow/trainer-controller-manager:latest
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --metrics-bind-address=0
            - --metrics-secure=true
            - --health-probe-bind-address=:8081
            - --enable-http2=false
            - --webhook-server-port=9443
            - --webhook-service-name=kubeflow-trainer-controller-service
            - --webhook-secret-name=kubeflow-trainer-webhook-cert
            - --leader-elect=false
          volumeMounts:
            - name: webhook-cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
      volumes:
        - name: webhook-cert
          secret:
            secretName: kubeflow-trainer-webhook-cert
            defaultMode: 420
      serviceAccountName: kubeflow-trainer-controller
      automountServiceAccountToken: true
