# Dockerfile used by out prow jobs.
# The sole purpose of this image is to customize the command run.
FROM gcr.io/mlkube-testing/test-worker:latest
MAINTAINER kubeflow-team

ENTRYPOINT ["/usr/local/bin/run.sh"]

