apiVersion: kubeflow.org/v1
kind: XGBoostJob
metadata:
  name: xgboost-dist-test
spec:
  xgbReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
          - name: xgboost
            image: docker.io/kubeflow/xgboost-dist-rabit-test:latest
            ports:
            - containerPort: 9991
              name: xgboostjob-port
            imagePullPolicy: Always
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
          - name: xgboost
            image: docker.io/kubeflow/xgboost-dist-rabit-test:latest
            ports:
            - containerPort: 9991
              name: xgboostjob-port
            imagePullPolicy: Always
