FROM gcr.io/tensorflow/tensorflow:1.3.0-rc2
RUN mkdir -p /opt/mlkube
RUN pip install python-json-logger wrapt
COPY tf_smoke.py /opt/mlkube/
COPY sitecustomize.py /opt/mlkube/
ENTRYPOINT ["python", "/opt/mlkube/tf_smoke.py"]
