apiVersion: "kubeflow.org/v1beta1"
kind: "TFJob"
metadata:
  name: "distributed-training"
  namespace: "kf-latest"
spec:
  cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 3 
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: gcr.io/kubeflow-examples/distributed_worker:v20181031-513e107c 
