// Copyright 2024 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v2alpha1 "github.com/kubeflow/training-operator/pkg/apis/trainer.kubeflow.org/v2alpha1"
	internal "github.com/kubeflow/training-operator/pkg/client/applyconfiguration/internal"
	trainerkubefloworgv2alpha1 "github.com/kubeflow/training-operator/pkg/client/applyconfiguration/trainer.kubeflow.org/v2alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=trainer.kubeflow.org, Version=v2alpha1
	case v2alpha1.SchemeGroupVersion.WithKind("ClusterTrainingRuntime"):
		return &trainerkubefloworgv2alpha1.ClusterTrainingRuntimeApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("ContainerOverride"):
		return &trainerkubefloworgv2alpha1.ContainerOverrideApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("CoschedulingPodGroupPolicySource"):
		return &trainerkubefloworgv2alpha1.CoschedulingPodGroupPolicySourceApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("DatasetConfig"):
		return &trainerkubefloworgv2alpha1.DatasetConfigApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("InputModel"):
		return &trainerkubefloworgv2alpha1.InputModelApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("JobSetTemplateSpec"):
		return &trainerkubefloworgv2alpha1.JobSetTemplateSpecApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("JobStatus"):
		return &trainerkubefloworgv2alpha1.JobStatusApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("MLPolicy"):
		return &trainerkubefloworgv2alpha1.MLPolicyApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("MLPolicySource"):
		return &trainerkubefloworgv2alpha1.MLPolicySourceApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("ModelConfig"):
		return &trainerkubefloworgv2alpha1.ModelConfigApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("MPIMLPolicySource"):
		return &trainerkubefloworgv2alpha1.MPIMLPolicySourceApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("OutputModel"):
		return &trainerkubefloworgv2alpha1.OutputModelApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("PodGroupPolicy"):
		return &trainerkubefloworgv2alpha1.PodGroupPolicyApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("PodGroupPolicySource"):
		return &trainerkubefloworgv2alpha1.PodGroupPolicySourceApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("PodSpecOverride"):
		return &trainerkubefloworgv2alpha1.PodSpecOverrideApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("PodSpecOverrideTargetJob"):
		return &trainerkubefloworgv2alpha1.PodSpecOverrideTargetJobApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("RuntimeRef"):
		return &trainerkubefloworgv2alpha1.RuntimeRefApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("TorchElasticPolicy"):
		return &trainerkubefloworgv2alpha1.TorchElasticPolicyApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("TorchMLPolicySource"):
		return &trainerkubefloworgv2alpha1.TorchMLPolicySourceApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("Trainer"):
		return &trainerkubefloworgv2alpha1.TrainerApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("TrainingRuntime"):
		return &trainerkubefloworgv2alpha1.TrainingRuntimeApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("TrainingRuntimeSpec"):
		return &trainerkubefloworgv2alpha1.TrainingRuntimeSpecApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("TrainJob"):
		return &trainerkubefloworgv2alpha1.TrainJobApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("TrainJobSpec"):
		return &trainerkubefloworgv2alpha1.TrainJobSpecApplyConfiguration{}
	case v2alpha1.SchemeGroupVersion.WithKind("TrainJobStatus"):
		return &trainerkubefloworgv2alpha1.TrainJobStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) *testing.TypeConverter {
	return &testing.TypeConverter{Scheme: scheme, TypeResolver: internal.Parser()}
}
