apiVersion: kubeflow.org/v1
kind: XGBoostJob
metadata:
  name: xgboost-dist-iris-test-train-local
spec:
  xgbReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        apiVersion: v1
        kind: Pod
        spec:
          volumes:
          - name: task-pv-storage
            persistentVolumeClaim:
              claimName: xgboostlocal
          containers:
          - name: xgboostjob
            image: docker.io/merlintang/xgboost-dist-iris:1.1
            volumeMounts:
              - name: task-pv-storage
                mountPath: /tmp/xgboost_model
            ports:
            - containerPort: 9991
              name: xgboostjob-port
            imagePullPolicy: Always
            args:
              - --job_type=Train
              - --xgboost_parameter=objective:multi:softprob,num_class:3
              - --n_estimators=10
              - --learning_rate=0.1
              - --model_path=/tmp/xgboost_model/2
              - --model_storage_type=local
    Worker:
      replicas: 2
      restartPolicy: ExitCode
      template:
        apiVersion: v1
        kind: Pod
        spec:
          volumes:
          - name: task-pv-storage
            persistentVolumeClaim:
              claimName: xgboostlocal
          containers:
          - name: xgboostjob
            image: docker.io/merlintang/xgboost-dist-iris:1.1
            volumeMounts:
              - name: task-pv-storage
                mountPath: /tmp/xgboost_model
            ports:
            - containerPort: 9991
              name: xgboostjob-port
            imagePullPolicy: Always
            args:
              - --job_type=Train
              - --xgboost_parameter="objective:multi:softprob,num_class:3"
              - --n_estimators=10
              - --learning_rate=0.1
              - --model_path=/tmp/xgboost_model/2
              - --model_storage_type=local
