apiVersion: kubeflow.org/v1
kind: XGBoostJob
metadata:
  name: xgboost-dist-iris-test-predict-local
spec:
  xgbReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          volumes:
          - name: task-pv-storage
            persistentVolumeClaim:
              claimName: xgboostlocal
          containers:
          - name: xgboost
            image: docker.io/kubeflow/xgboost-dist-iris:latest
            volumeMounts:
              - name: task-pv-storage
                mountPath: /tmp/xgboost_model
            ports:
            - containerPort: 9991
              name: xgboostjob-port
            imagePullPolicy: Always
            args:
              - --job_type=Predict
              - --model_path=/tmp/xgboost_model/2
              - --model_storage_type=local
    Worker:
      replicas: 2
      restartPolicy: ExitCode
      template:
        spec:
          volumes:
          - name: task-pv-storage
            persistentVolumeClaim:
              claimName: xgboostlocal
          containers:
          - name: xgboost
            image: docker.io/kubeflow/xgboost-dist-iris:latest
            volumeMounts:
              - name: task-pv-storage
                mountPath: /tmp/xgboost_model
            ports:
            - containerPort: 9991
              name: xgboostjob-port
            imagePullPolicy: Always
            args:
             - --job_type=Predict
             - --model_path=/tmp/xgboost_model/2
             - --model_storage_type=local
