# Docker image for running examples in Tensorflow models.
# base_image depends on whether we are running on GPUs or non-GPUs
FROM {{base_image}}

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    git

# Checkout tensorflow/models and pin to a particular version
RUN git clone https://github.com/tensorflow/models.git /tensorflow_models && \
    cd /tensorflow_models && \
    git checkout d86aa76
