name: tf-job-operator-chart
home: https://github.com/jlewi/mlkube.io
version: 0.1.0
appVersion: 0.1.0
description: K8s Third Party Resource and Operator For TensorFlow jobs
icon: https://raw.githubusercontent.com/hashicorp/consul/bce3809dfca37b883828c3715b84143dd71c0f85/website/source/assets/images/favicons/android-chrome-512x512.png
sources:
  - https://github.com/jlewi/mlkube.io
