# coding: utf-8

"""
    Kubeflow Trainer OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kubeflow.trainer.configuration import Configuration


class TrainerV1alpha1TrainingRuntimeSpec(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ml_policy': 'TrainerV1alpha1MLPolicy',
        'pod_group_policy': 'TrainerV1alpha1PodGroupPolicy',
        'template': 'TrainerV1alpha1JobSetTemplateSpec'
    }

    attribute_map = {
        'ml_policy': 'mlPolicy',
        'pod_group_policy': 'podGroupPolicy',
        'template': 'template'
    }

    def __init__(self, ml_policy=None, pod_group_policy=None, template=None, local_vars_configuration=None):  # noqa: E501
        """TrainerV1alpha1TrainingRuntimeSpec - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._ml_policy = None
        self._pod_group_policy = None
        self._template = None
        self.discriminator = None

        if ml_policy is not None:
            self.ml_policy = ml_policy
        if pod_group_policy is not None:
            self.pod_group_policy = pod_group_policy
        self.template = template

    @property
    def ml_policy(self):
        """Gets the ml_policy of this TrainerV1alpha1TrainingRuntimeSpec.  # noqa: E501


        :return: The ml_policy of this TrainerV1alpha1TrainingRuntimeSpec.  # noqa: E501
        :rtype: TrainerV1alpha1MLPolicy
        """
        return self._ml_policy

    @ml_policy.setter
    def ml_policy(self, ml_policy):
        """Sets the ml_policy of this TrainerV1alpha1TrainingRuntimeSpec.


        :param ml_policy: The ml_policy of this TrainerV1alpha1TrainingRuntimeSpec.  # noqa: E501
        :type: TrainerV1alpha1MLPolicy
        """

        self._ml_policy = ml_policy

    @property
    def pod_group_policy(self):
        """Gets the pod_group_policy of this TrainerV1alpha1TrainingRuntimeSpec.  # noqa: E501


        :return: The pod_group_policy of this TrainerV1alpha1TrainingRuntimeSpec.  # noqa: E501
        :rtype: TrainerV1alpha1PodGroupPolicy
        """
        return self._pod_group_policy

    @pod_group_policy.setter
    def pod_group_policy(self, pod_group_policy):
        """Sets the pod_group_policy of this TrainerV1alpha1TrainingRuntimeSpec.


        :param pod_group_policy: The pod_group_policy of this TrainerV1alpha1TrainingRuntimeSpec.  # noqa: E501
        :type: TrainerV1alpha1PodGroupPolicy
        """

        self._pod_group_policy = pod_group_policy

    @property
    def template(self):
        """Gets the template of this TrainerV1alpha1TrainingRuntimeSpec.  # noqa: E501


        :return: The template of this TrainerV1alpha1TrainingRuntimeSpec.  # noqa: E501
        :rtype: TrainerV1alpha1JobSetTemplateSpec
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this TrainerV1alpha1TrainingRuntimeSpec.


        :param template: The template of this TrainerV1alpha1TrainingRuntimeSpec.  # noqa: E501
        :type: TrainerV1alpha1JobSetTemplateSpec
        """
        if self.local_vars_configuration.client_side_validation and template is None:  # noqa: E501
            raise ValueError("Invalid value for `template`, must not be `None`")  # noqa: E501

        self._template = template

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrainerV1alpha1TrainingRuntimeSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TrainerV1alpha1TrainingRuntimeSpec):
            return True

        return self.to_dict() != other.to_dict()
